Repository FaculdadeSenaiJoinville/penelope, pull requests merged in 2021-11, with the labels that each got.

#39 PES 348/345 - Ajustes nas modais de Criação/O tipo de usuário não vem pré-selecionado
  components/buttons/OButton.vue
  components/inputs/OSelectList.vue
  pages/users/edit.vue
  pages/users/new.vue
Labels: bug, code review

#40 PES-346 - Validação que no nome tenha pelo menos um espaço para obrigar a colocar nome e sobrenome
  components/ORequiredSymbol.vue
  components/buttons/OToggleSwitch.vue
  components/inputs/OInput.vue
  components/inputs/OSelectList.vue
Labels: bug, code review

#41 Instalar Vuetify
  components/modal/OModal.vue
  config/build-modules.config.ts
  config/build.config.ts
  config/plugins.config.ts
  package.json
  plugins/vuetify.ts
  yarn.lock
Labels: dependencies, code review

#42 Modal de detalhes de grupos
  components/OGroupMembers.vue
  package.json
  pages/groups/details.vue
  types/entities/group.type.ts
Labels: feature, code review

#44 PES-342 - Tela de login está fazendo uma requisição para "/me"
  layouts/default.vue
  package.json
  yarn.lock
Labels: bug

#43 Tela de listagem de grupos
  components/dashboards/AdminDashboard.vue
  components/dashboards/ProfessorDashboard.vue
  pages/groups/index.vue
  types/entities/group.type.ts
  types/entities/index.ts
Labels: feature, code review

#45 PES-313 - Modal de excluir grupos
  package.json
  pages/groups/delete.vue
  pages/groups/index.vue
  yarn.lock
Labels: feature, code review

#46 PES-314 - Modificar modal de criar/editar/detalhes de usuários
  components/OGroup.vue
  package.json
  pages/groups/details.vue
  pages/users/details.vue
  pages/users/edit.vue
  pages/users/new.vue
  types/components/o-group.type.ts
  types/entities/user.type.ts
  yarn.lock
Labels: feature, code review

#47 PES-312 - Modal de editar grupos
  assets/styles/input.css
  components/OGroup.vue
  components/OGroupMembers.vue
  components/inputs/OInput.vue
  components/inputs/OSearchBar.vue
  package.json
  pages/groups/delete.vue
  pages/groups/edit.vue
  pages/groups/index.vue
  pages/users/details.vue
  pages/users/edit.vue
  pages/users/new.vue
  types/components/o-group.type.ts
  types/entities/group.type.ts
  types/entities/user.type.ts
  yarn.lock
Labels: feature, code review

#50 PES-355 - Histórico do chatbot
  components/buttons/OActionButtons.vue
  pages/botHistories/details.vue
  pages/botHistories/index.vue
  types/entities/bot-history.type.ts
  types/entities/index.ts
Labels: feature, code review

#51 PES-356 - Corrigir problemas com content
  components/inputs/OInput.vue
  pages/contents/delete.vue
  pages/contents/index.vue
Labels: code review
