Repository FaculdadeSenaiJoinville/penelope, pull requests merged in 2021-08, with the labels that each got.

#15 PES-251 - Search bar
  assets/styles/button.css
  assets/styles/global.css
  assets/styles/input.css
  components/OCard.vue
  components/buttons/OActionButtons.vue
  components/buttons/OButton.vue
  components/inputs/OInput.vue
  components/inputs/OSearchBar.vue
  components/inputs/OSelectList.vue
  index.d.ts
  layouts/default.vue
  layouts/error.vue
  nuxt.config.ts
  pages/dev/components.vue
  pages/login.vue
  plugins/global.mixin.ts
  types/components/o-action-buttons.type.ts
  types/components/o-modal.type.ts
  types/components/o-select-list.type.ts
Labels: feature, code review

#17 PES-241 - Desenvolver a modal de cadastro de usuários
  assets/styles/global.css
  components/OIcon.vue
  components/buttons/OActionCard.vue
  components/buttons/OButton.vue
  components/dashboards/AdminDashboard.vue
  components/dashboards/ProfessorDashboard.vue
  components/dashboards/StudentDashboard.vue
  components/inputs/OInput.vue
  components/inputs/OSelectList.vue
  components/modal/OModalHeader.vue
  nuxt.config.ts
  package.json
  pages/dev/components.vue
  pages/index.vue
  pages/users/new.vue
  plugins/global.mixin.ts
  tsconfig.json
  types/components/o-modal.type.ts
  types/entities/user.type.ts
  types/global.mixin.type.ts
  yarn.lock
Labels: feature, code review

#16 PES-222 - Modificar para ficar dentro do padrão (Login)
  assets/styles/input.css
  components/OCard.vue
  components/inputs/OInput.vue
  nuxt.config.ts
  pages/login.vue
  static/illustrations/skate.svg
Labels: feature, code review

#19 Corrigindo action do botão de login
  pages/login.vue
Labels: bug, code review

#24 PES-243 - Deploy do Penelope
  .github/workflows/deploy.yml
  .vercelignore
  assets/styles/variables.scss
  config/auth.config.ts
  config/axios.config.ts
  config/build-modules.config.ts
  config/build.config.ts
  config/css.config.ts
  config/head.config.ts
  config/modules.config.ts
  config/plugins.config.ts
  config/router.config.ts
  config/server.config.ts
  config/toast.config.ts
  config/vuetify.config.ts
  package.json
  vercel.json
  yarn.lock
Labels: code review

#21 PES-238 - Desenvolver a modal de editar usuário
  pages/users/edit.vue
  plugins/global.mixin.ts
  types/entities/user.type.ts
Labels: feature, code review

#22 PES-239 - Desenvolver a modal de mudar status do usuário
  package.json
  pages/users/update-status.vue
  types/entities/user.type.ts
Labels: feature, code review

#23 PES-240 - Desenvolver a tela de perfil
  assets/styles/button.css
  assets/styles/global/global.css
  assets/styles/global/spaces.css
  assets/styles/input.css
  components/OField.vue
  components/buttons/OActionCard.vue
  components/inputs/OInput.vue
  components/inputs/OSelectList.vue
  components/modal/OModalFooter.vue
  components/modal/OModalHeader.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/dev/components.vue
  pages/login.vue
  pages/profile.vue
  pages/users/new.vue
  pages/users/update-status.vue
  plugins/global.mixin.ts
  types/entities/user.type.ts
  types/global.mixin.type.ts
  yarn.lock
Labels: feature, code review
